# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgapp', '0002_auto_20161118_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_set',
        ),
        migrations.AddField(
            model_name='card',
            name='sets',
            field=models.ManyToManyField(blank=True, related_name='card', to='mtgapp.CardSet'),
        ),
    ]
